### ISSUE TITLE
README.md is outdated

### ISSUE THREAD

**Issue by pockany** [googlecast/CastHelloVideo-ios#1]
README.md is outdated since 06f5c6055aac07f775748bd56f2d64b61ffda325 ( https://github.com/googlecast/CastHelloVideo-ios/commit/06f5c6055aac07f775748bd56f2d64b61ffda325 ).

This part should be updated : 
"In HGCVViewController.m, replace @"YOUR_APP_ID_HERE" with your app identifier from the Google Cast Developer Console. When you are done, it will look something like:
static NSString *const kReceiverAppID = @"1234ABCD";"

**Comment by cassierecher** [comment]
Is this still an issue?

**Comment by cassierecher** [comment]
Closing issue, apparently stale or resolved.

**Comment by naoufalmed** [comment]
Well, as far as I can see, it is still an issue :-)
 Here is how it does look now in the code (Obj-C):

``` objc
   static NSString * kReceiverAppID;
//...
//...

  // You can add your own app id here that you get by registering with the Google Cast SDK
  // Developer Console https://cast.google.com/publish
  kReceiverAppID=kGCKMediaDefaultReceiverApplicationID;
```

... and for Swift:

``` swift
    private lazy var kReceiverAppID:String = {
    // You can add your own app id here that you get by registering with the
    // Google Cast SDK Developer Console https://cast.google.com/publish
    return kGCKMediaDefaultReceiverApplicationID
    }()
```
