### ISSUE TITLE
Errors on Pod Install

### ISSUE THREAD

**Issue by tooolbox** [googlecast/CastHelloVideo-ios#10]
> `!] Invalid 'Podfile' file: [!] The specification of 'link_with' in the Podfile is now unsupported, please use target blocks instead..`

I have Cocoapods v1.4.0

**Comment by rtrigoso** [comment]
the podfile is outdated. You need to update your podfile to use target instead of link_with. I added a pull request for this: https://github.com/googlecast/CastHelloVideo-ios/pull/13

**Comment by jtromo** [comment]
This has been addressed. See the updated podfile.
