### ISSUE TITLE
Mirroring/showing screen/viewcontroller only rather playing video in iOS CastSDK

### ISSUE THREAD

**Issue by jams032** [googlecast/CastHelloVideo-ios#17]
I was looking for a solution to mirroring my iOS app screen rather playing video from app. My intension is to show the app screen in larger screen while users use our fitness app. I can perform it from iOS AirPlay(shares whole iOS device to apple TV or supported TV screen) but i want it from iOS Cast SDK too.

I already have bought a CAST DEVELOPER ACCOUNT(5USD)  but having no proper way to do it yet.  

My queries are : 
- Is it possible with CAST IOS SDK ?
- Which API should be used?
- Any proper sample to screen mirror/app screen sharing? 
 
Any clue/workaround would be a great help. 

Update: If CAST iOS SDK does not provide screen mirroring(iPhone to airplay supported tv/smart TV ), what should be the best way to implement this? Any hope with letsview.com or BJcast SDK or anything? 

Thanks in advance guys.

**Comment by jtromo** [comment]
This use case is no longer supported.
