### ISSUE TITLE
Cannot detect any chromecast devices

### ISSUE THREAD

**Issue by Smashkon** [googlecast/CastHelloVideo-ios#6]
Hi,
I'm having trouble getting the HelloVideoGoogleCast app to work. It doesn't detect any chromecast devices on my network. Any help would be appreciated. Here are logs from the app:

2016-01-05 14:38:58.555 HelloVideoGoogleCastSwift[241:9290] GoogleCast framework version 2.10.1.4691
-[GCKDeviceScanner startScan] - reachability start monitoring
-[GCKNetworkReachability startMonitoring] - startMonitoring
-[GCKNetworkReachability startMonitoring] - requesting current status
-[GCKNetworkReachability updateStatusFromFlags:] - updateStatusFromFlags
-[GCKNetworkReachability updateStatusFromFlags:] - statusChanged=1, _currentStatus=1, _currentBSSID=84:db:2f:43:e9:7b
-[GCKNetworkReachability updateStatusFromFlags:] - status or BSSID has changed
-[GCKDeviceScanner networkReachabilityStatusDidChange:networkDidChange:] - networkReachabilityStatusDidChange:1 networkDidChange:1
-[GCKDeviceScanner purgeAllOnlineDevices] - purgeAllOnlineDevices
-[GCKDeviceScanner networkReachabilityStatusDidChange:networkDidChange:] - Restarting scan after WiFi acquired or network changed
+[NSMutableDictionary(GCKAdditions) gck_loadFromCacheWithName:] - Device cache file file:///var/mobile/Containers/Data/Application/039829F1-019C-40B4-98B1-B09B60D5D76A/Library/Caches/gck_device_cache_v1.plist doesn't exist.
-[GCKDeviceScanner startNetServiceScan] - startNetServiceScan
-[GCKDeviceScanner startNetServiceScan] - querying for subtype: _CC1AD845
-[GCKDeviceScanner netServiceBrowser:didFindService:moreComing:] - found Chromecast9749,(null)
-[GCKDeviceScanner startResolveForEntry:] - resolving Chromecast9749
-[GCKDeviceScanner netServiceDidResolveAddress:] - resolved address for 'Chromecast9749'
-[GCKDeviceScanner updateDeviceEntryForService:] - updateDeviceEntryForService: 'Chromecast9749'
-[GCKDeviceScanner maybePublishDevice:] - maybePublishDevice: 0x170300900:GCKDevice 'Chromecast9749' (4bf63f7f90e90a176b046920b9bbc966)
-[GCKDeviceScanner maybePublishDevice:] - [A] starting legacy filtering for 0x170300900:GCKDevice 'Chromecast9749' (4bf63f7f90e90a176b046920b9bbc966)
-[GCKDeviceScanner startFilteringDevice:] - starting filter for device: 0x170300900:GCKDevice 'Chromecast9749' (4bf63f7f90e90a176b046920b9bbc966) with filter CC1AD845 - attempt 0
-[GCKClientCertificate init] - Failed to query KeyChain for idenities err=-25300
-[GCKDeviceManager connectInternalUnchecked] - connectInternalUnchecked to Chromecast9749
-[GCKClearcutLogger scanLogCache] - enqueuing request for log file: /var/mobile/Containers/Data/Application/039829F1-019C-40B4-98B1-B09B60D5D76A/Library/Caches/GCKClearcutLogger/67/2016.01.05.14.38.48.016
-[GCKEventLogger logDeviceControllerConnecting:sessionID:] - LOG EVENT: hashedDeviceID=-8180151354301140754, sessionID=266192783
-[GCKClearcutLogger logEvent:fromSource:] - logging an event from source: 67
-[GCKCastSecureSocket connectToHost:port:withTimeout:] - leaving connectToHost
-[GCKEventLogger logFilterConnectingToDevice:sessionID:filterID:] - LOG EVENT: hashedDeviceID=-8180151354301140754, sessionID=266192578
-[GCKClearcutLogger logEvent:fromSource:] - logging an event from source: 67
__41-[GCKClearcutLogger logEvent:fromSource:]_block_invoke - opening new log file in: /var/mobile/Containers/Data/Application/039829F1-019C-40B4-98B1-B09B60D5D76A/Library/Caches/GCKClearcutLogger/67/2016.01.05.14.38.58.838
-[GCKBLEDeviceVisibilityChecker centralManagerDidUpdateState:] - State: Powered On
-[GCKClearcutLogWriter open] - opened log file: /var/mobile/Containers/Data/Application/039829F1-019C-40B4-98B1-B09B60D5D76A/Library/Caches/GCKClearcutLogger/67/2016.01.05.14.38.58.838
-[GCKCastSecureSocket stream:handleEvent:] - handle read stream event: 1
-[GCKCastSecureSocket stream:handleEvent:] - handshaking=1
-[GCKCastSecureSocket stream:handleEvent:] - handle write stream event: 1
-[GCKCastSecureSocket stream:handleEvent:] - handshaking=1
-[GCKCastSecureSocket stream:handleEvent:] - handle write stream event: 4
-[GCKCastSecureSocket stream:handleEvent:] - handshaking=1
-[GCKCastSecureSocket stream:handleEvent:] - handle read stream event: 2
-[GCKCastSecureSocket stream:handleEvent:] - handshaking=1
-[GCKCastSecureSocket stream:handleEvent:] - handle read stream event: 2
-[GCKCastSecureSocket stream:handleEvent:] - handshaking=0
-[GCKCastSecureSocket stream:handleEvent:] - handle read stream event: 2
-[GCKCastSecureSocket stream:handleEvent:] - handshaking=0
-[GCKCastSecureSocket stream:handleEvent:] - handle read stream event: 2
-[GCKCastSecureSocket stream:handleEvent:] - handshaking=0
-[GCKDeviceAuthChannel didReceiveBinaryMessage:] - Genuine Google device didDeviceAuthenticated=YES
-[GCKDeviceManager deviceAuthChannelDidAuthenticate:] - Authentic device, connecting receiver channel
-[GCKDeviceManager connectToReceiverChannel] - connectToReceiverChannel; isReconnecting is 0
-[GCKCastChannel sendTextMessage:toDestinationID:] - sending message on urn:x-cast:com.google.cast.tp.connection: {"userAgent":"iOS CastSDK,2.10.1,iPhone,iPhone OS,8.4","type":"CONNECT","origin":{"package":"com.google.cast.DeviceFilter"},"senderInfo":{"platform":2,"systemVersion":"8.4","sdkType":1,"model":"iPhone","connectionType":1,"version":"2.10.1"}}
-[GCKEventLogger logDeviceControllerConnected:sessionID:] - LOG EVENT: hashedDeviceID=-8180151354301140754, sessionID=266192783
-[GCKClearcutLogger logEvent:fromSource:] - logging an event from source: 67
-[GCKDeviceFilter deviceManagerDidConnect:] - deviceManagerDidConnect
-[GCKEventLogger logFilterConnectedToDevice:sessionID:filterID:] - LOG EVENT: hashedDeviceID=-8180151354301140754, sessionID=266192578
-[GCKClearcutLogger logEvent:fromSource:] - logging an event from source: 67
-[GCKCastChannel sendTextMessage:toDestinationID:] - sending message on urn:x-cast:com.google.cast.setup: {"type":"eureka_info","request_id":1,"data":{"params":["version","name","device_info.ssdp_udn","build_info.cast_build_revision","net.ip_address","net.online","wifi.ssid","wifi.signal_level","wifi.noise_level"]}}
-[GCKCastChannel sendTextMessage:toDestinationID:] - sending message on urn:x-cast:com.google.cast.receiver: {"type":"GET_STATUS","requestId":2}
-[GCKProximityInfoChannel initiateGetProximityInfo] - initiateGetProximityInfo
-[GCKCastChannel sendTextMessage:toDestinationID:] - sending message on urn:x-cast:com.google.cast.proximity: {"type":"GET_PROXIMITY_INFO","requestId":3}
-[GCKCastSecureSocket stream:handleEvent:] - handle read stream event: 2
-[GCKCastSecureSocket stream:handleEvent:] - handshaking=0
-[GCKCastSecureSocket stream:handleEvent:] - handle read stream event: 2
-[GCKCastSecureSocket stream:handleEvent:] - handshaking=0
-[GCKReceiverControlChannel didReceiveTextMessage:] - received: {"requestId":2,"status":{"applications":[{"appId":"00000000-0000-0000-0000-000000000000","displayName":"IMAX","sessionId":"7C0A5CCD-6815-5A3E-617F-E729718B9A5F","statusText":"Chromecast Home Screen"}],"volume":{"level":1.0,"muted":false}},"type":"RECEIVER_STATUS"}
-[GCKDeviceManager receiverControlChannel:didReceiveReceiverStatus:applicationStatus:requestID:] - Received device status with requestID=2
-[GCKDeviceManager receiverControlChannel:didReceiveReceiverStatus:applicationStatus:requestID:] - checking if app is stopped
-[GCKDeviceManager receiverControlChannel:didReceiveReceiverStatus:applicationStatus:requestID:] - checking receiver status for changes; status was requested? 1
-[GCKDeviceManager receiverControlChannel:didReceiveReceiverStatus:applicationStatus:requestID:] - status text has changed; calling delegate
-[GCKDeviceManager receiverControlChannel:didReceiveReceiverStatus:applicationStatus:requestID:] - volume has changed; calling delegate
-[GCKDeviceManager receiverControlChannel:didReceiveReceiverStatus:applicationStatus:requestID:] - active input status has changed; calling delegate
-[GCKDeviceManager receiverControlChannel:didReceiveReceiverStatus:applicationStatus:requestID:] - standby status has changed; calling delegate
-[GCKDeviceFilter deviceManagerDidUpdateStatus:] - deviceManagerDidUpdateStatus for Chromecast9749
-[GCKEventLogger logFilterReceivedStatusForDevice:sessionID:filterID:] - LOG EVENT: hashedDeviceID=-8180151354301140754, sessionID=266192578
-[GCKClearcutLogger logEvent:fromSource:] - logging an event from source: 67
-[GCKDeviceFilter deviceManagerDidUpdateStatus:] - requesting availability of CC1AD845
-[GCKCastChannel sendTextMessage:toDestinationID:] - sending message on urn:x-cast:com.google.cast.receiver: {"type":"GET_APP_AVAILABILITY","requestId":4,"appId":["CC1AD845"]}
-[GCKEventLogger logFilterRequestedAppAvailabilityForDevice:sessionID:filterID:] - LOG EVENT: hashedDeviceID=-8180151354301140754, sessionID=266192578
-[GCKClearcutLogger logEvent:fromSource:] - logging an event from source: 67
-[GCKCastSecureSocket stream:handleEvent:] - handle read stream event: 2
-[GCKCastSecureSocket stream:handleEvent:] - handshaking=0
-[GCKReceiverControlChannel didReceiveTextMessage:] - received: {"availability":{"CC1AD845":"APP_AVAILABLE"},"requestId":4,"responseType":"GET_APP_AVAILABILITY"}
-[GCKDeviceFilter deviceManager:didReceiveAppAvailability:] - didReceiveAppAvailability: {
    CC1AD845 = 1;
} for Chromecast9749
-[GCKEventLogger logFilterReceivedAppAvailabilityForDevice:sessionID:filterID:] - LOG EVENT: hashedDeviceID=-8180151354301140754, sessionID=266192578
-[GCKClearcutLogger logEvent:fromSource:] - logging an event from source: 67
-[GCKDeviceFilter deviceManager:didReceiveAppAvailability:] - available? 1
-[GCKDeviceScanner mdnsDiscoveryTimeoutTimerDidFire:] - mdnsDiscoveryTimeoutTimerDidFire﻿

**Comment by cassierecher** [comment]
Your Chromecast device is named "Chromecast9749", correct? Also, do you have mDNS enabled?

**Comment by Smashkon** [comment]
Hi,
Yes that is the name of the chromecast, it shows up in the logs but doesn't give me the ability to connect to it. I have verified that the chromecast is visible on the network using a bonjour scanner. Other apps like Youtube and Netflix seem to detect the chromecast and connect.

**Comment by cassierecher** [comment]
I need some more data - is this on a physical device, or the simulator? Which device and iOS version? Is it one of the new form factor Chromecasts, or an older one?

**Comment by Smashkon** [comment]
Its a physical device, iPhone 6S running iOS 9.2. Old chromecast

**Comment by Smashkon** [comment]
I'm using the default filter criteria in the sample app

**Comment by cassierecher** [comment]
I can't reproduce this with the named hardware and version. Does the [CastVideos](https://github.com/googlecast/CastVideos-ios) sample app work?

**Comment by Smashkon** [comment]
It looks like there is an issue with the latest google cast SDK. I downgraded to 2.7.1, worked perfectly. I'm able to replicate this every time with 4 different iPhone 6's and 6s on iOS 9.2. Using multiple different wifi networks with the same chromecast

**Comment by cassierecher** [comment]
Sounds like a bug to me. Please report this on the [Cast SDK issue tracker](https://code.google.com/p/google-cast-sdk/issues/list). Thanks!

**Comment by Jesse-calkin** [comment]
I was unable to find the issue mentioned above, so I [filed one here.](https://code.google.com/p/google-cast-sdk/issues/detail?id=751)

**Comment by naveenshan01** [comment]
Might Help someone : I also experienced the same issue with "GoogleCastSDK-2.10.4-Release", But it got fixed after adding -ObjC in other linker flags.

**Comment by anilo** [comment]
im also getting "Not Connected". "Please connect to cast device".

Every other application works. 
Youtube, Udemy, etc. 
Also, I configured my chromecast device to work with my ios device using the chromecast app.
