### ISSUE TITLE
Add support for MacOS

### ISSUE THREAD

**Issue by justinjdickow** [googlecast/CastHelloVideo-ios#7]
it would be awesome to see this library add support for MacOS apps. example: https://github.com/insidegui/WWDC/issues/86

**Comment by anjaneesh** [comment]
Hello, can you please file a feature request through public issue tracker.
https://developers.google.com/cast/support

Thanks!

**Comment by justinjdickow** [comment]
Lol no, I don't even remember what this is. It's three years later
